-- conn sys/oracle as sysdba;
-- create user PH identified by PH;
-- grant unlimited tablespace to PH;
-- grant all privileges to PH;
-- CREATE TABLESPACE D01 DATAFILE '/u01/app/oracle/oradata/XE/D01.dbf' SIZE 5120M;
-- CREATE TABLESPACE I01 DATAFILE '/u01/app/oracle/oradata/XE/I01.dbf' SIZE 5120M;
-- CREATE TABLESPACE L01 DATAFILE '/u01/app/oracle/oradata/XE/L01.dbf' SIZE 5120M;
-- alter system set processes=300 scope=spfile;
-- alter system set sessions=300 scope=spfile;
--
-- shutdown immediate;
-- startup;
-- disc;
--
--
-- conn PH/PH;
-- create role PH_DELETE;
-- create role  PH_INSERT;
-- create role  PH_UPDATE;
-- create role  PH_SELECT;
-- create user PHUSR identified by PHUSR;
-- grant create session to PHUSR;
-- grant PH_DELETE to PHUSR;
-- grant PH_INSERT to PHUSR;
-- grant PH_UPDATE to PHUSR;
-- grant PH_SELECT to PHUSR;
--
-- disc;



CREATE TABLE PHOTO_HASH
(
    ID         NUMBER(18)           NOT NULL,
    PHOTO_ID   NUMBER(18)           NOT NULL,
    P_HASH     NUMBER(38),
    A_HASH     NUMBER(38),
    D_HASH64  NUMBER(38),
    D_HASH16  NUMBER(38),
    CREATED_DT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_DT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PH1 PRIMARY KEY (ID)
        USING INDEX TABLESPACE I01
) TABLESPACE D01;

CREATE SEQUENCE PHOTO_HASH_IDSEQ START WITH 1 NOCYCLE CACHE 50 NOORDER;

GRANT DELETE ON PHOTO_HASH TO PH_DELETE;
GRANT INSERT ON PHOTO_HASH TO PH_INSERT;
GRANT SELECT ON PHOTO_HASH TO PH_SELECT;
GRANT UPDATE ON PHOTO_HASH TO PH_UPDATE;
GRANT SELECT ON PHOTO_HASH_IDSEQ TO PH_SELECT;



CREATE TABLE PHOTO
(
    ID         NUMBER(18)           NOT NULL,
    PHOTO_DATA BLOB,
    CREATED_DT DATE DEFAULT SYSDATE NOT NULL,
    UPDATED_DT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT P1 PRIMARY KEY (ID) USING INDEX TABLESPACE I01
) TABLESPACE D01;

CREATE SEQUENCE PHOTO_IDSEQ START WITH 1 NOCYCLE CACHE 50 NOORDER;

GRANT DELETE ON PHOTO TO PH_DELETE;
GRANT INSERT ON PHOTO TO PH_INSERT;
GRANT SELECT ON PHOTO TO PH_SELECT;
GRANT UPDATE ON PHOTO TO PH_UPDATE;
GRANT SELECT ON PHOTO_IDSEQ TO PH_SELECT;